name = "Cobble Creations"
author = "jadelily18"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63c3421b670a884a664f970dd709e5a00ba32ed6dffb2486d32e7b87dfb899db"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
