name = "Cobble Creations"
author = "jadelily18"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b699e40f0e337b6050e40fa7afc371ca1c4fa6d6f9006252746fb8487632cdd"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
