name = "Cobble Creations"
author = "jadelily18"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f11c6cb9e6c29aa2c9aa51e36abe5da61ddb51f776e386524388bdd1331ba8e"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
