name = "Cobble Creations"
author = "jadelily18"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e5e0fd94ab660e5b5d7121fc2291059a782b426e5465fef5ffee0c146e16b98"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
