name = "Cobble Creations"
author = "jadelily18"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "471abd5ebc8a1d7d8c7764a2c7a484e5b8b058fd2bb744179fa1432b84e68cb3"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
